/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int COLON = 12;
  /** RegularExpression Id. */
  int IF = 13;
  /** RegularExpression Id. */
  int LOOP = 14;
  /** RegularExpression Id. */
  int REPEAT = 15;
  /** RegularExpression Id. */
  int DEFUN = 16;
  /** RegularExpression Id. */
  int DIM = 17;
  /** RegularExpression Id. */
  int MYXPOS = 18;
  /** RegularExpression Id. */
  int MYYPOS = 19;
  /** RegularExpression Id. */
  int MYCHIPS = 20;
  /** RegularExpression Id. */
  int MYBALLONS = 21;
  /** RegularExpression Id. */
  int BALLONSHERE = 22;
  /** RegularExpression Id. */
  int CHIPSHERE = 23;
  /** RegularExpression Id. */
  int SPACES = 24;
  /** RegularExpression Id. */
  int NULL = 25;
  /** RegularExpression Id. */
  int BALLOONS = 26;
  /** RegularExpression Id. */
  int CHIPS = 27;
  /** RegularExpression Id. */
  int NORTH = 28;
  /** RegularExpression Id. */
  int SOUTH = 29;
  /** RegularExpression Id. */
  int EAST = 30;
  /** RegularExpression Id. */
  int WEST = 31;
  /** RegularExpression Id. */
  int LEFT = 32;
  /** RegularExpression Id. */
  int AROUND = 33;
  /** RegularExpression Id. */
  int FRONT = 34;
  /** RegularExpression Id. */
  int BACK = 35;
  /** RegularExpression Id. */
  int UP = 36;
  /** RegularExpression Id. */
  int DOWN = 37;
  /** RegularExpression Id. */
  int NUM = 38;
  /** RegularExpression Id. */
  int DIGIT = 39;
  /** RegularExpression Id. */
  int DIGITO = 40;
  /** RegularExpression Id. */
  int LETRA = 41;
  /** RegularExpression Id. */
  int PALABRA = 42;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Mov\"",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\":\"",
    "\"if\"",
    "\"loop\"",
    "\"repead\"",
    "\"defun\"",
    "\"dim\"",
    "\"myxpos\"",
    "\"myypos\"",
    "\"mychips\"",
    "\"myballoons\"",
    "\"balloonshere\"",
    "\"chipsHere\"",
    "\"spaces\"",
    "\"null\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "\"left\"",
    "\"around\"",
    "\"front\"",
    "\"back\"",
    "\"up\"",
    "\"down\"",
    "<NUM>",
    "<DIGIT>",
    "<DIGITO>",
    "<LETRA>",
    "<PALABRA>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
  };

}
