/* Generated By:JavaCC: Do not edit this line. RobotConstants.java */
package uniandes.lym.robot.control;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RobotConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MOV = 5;
  /** RegularExpression Id. */
  int RIGHT = 6;
  /** RegularExpression Id. */
  int PUT = 7;
  /** RegularExpression Id. */
  int PICK = 8;
  /** RegularExpression Id. */
  int POP = 9;
  /** RegularExpression Id. */
  int GO = 10;
  /** RegularExpression Id. */
  int HOP = 11;
  /** RegularExpression Id. */
  int LEFT = 12;
  /** RegularExpression Id. */
  int AROUND = 13;
  /** RegularExpression Id. */
  int FRONT = 14;
  /** RegularExpression Id. */
  int BACK = 15;
  /** RegularExpression Id. */
  int UP = 16;
  /** RegularExpression Id. */
  int DOWN = 17;
  /** RegularExpression Id. */
  int DEFVAR = 18;
  /** RegularExpression Id. */
  int SKIPP = 19;
  /** RegularExpression Id. */
  int TURN = 20;
  /** RegularExpression Id. */
  int FACE = 21;
  /** RegularExpression Id. */
  int MOVEDIR = 22;
  /** RegularExpression Id. */
  int RUNDIRS = 23;
  /** RegularExpression Id. */
  int MOVEFACE = 24;
  /** RegularExpression Id. */
  int LP = 25;
  /** RegularExpression Id. */
  int RP = 26;
  /** RegularExpression Id. */
  int COLON = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int LOOP = 29;
  /** RegularExpression Id. */
  int REPEAT = 30;
  /** RegularExpression Id. */
  int DEFUN = 31;
  /** RegularExpression Id. */
  int BALLOONS = 32;
  /** RegularExpression Id. */
  int CHIPS = 33;
  /** RegularExpression Id. */
  int FACING = 34;
  /** RegularExpression Id. */
  int BLOCKED = 35;
  /** RegularExpression Id. */
  int CANPUT = 36;
  /** RegularExpression Id. */
  int CANPICK = 37;
  /** RegularExpression Id. */
  int CANMOVE = 38;
  /** RegularExpression Id. */
  int ISZERO = 39;
  /** RegularExpression Id. */
  int NOT = 40;
  /** RegularExpression Id. */
  int DIM = 41;
  /** RegularExpression Id. */
  int MYXPOS = 42;
  /** RegularExpression Id. */
  int MYYPOS = 43;
  /** RegularExpression Id. */
  int MYCHIPS = 44;
  /** RegularExpression Id. */
  int MYBALLONS = 45;
  /** RegularExpression Id. */
  int BALLONSHERE = 46;
  /** RegularExpression Id. */
  int CHIPSHERE = 47;
  /** RegularExpression Id. */
  int SPACES = 48;
  /** RegularExpression Id. */
  int NULL = 49;
  /** RegularExpression Id. */
  int NORTH = 50;
  /** RegularExpression Id. */
  int SOUTH = 51;
  /** RegularExpression Id. */
  int EAST = 52;
  /** RegularExpression Id. */
  int WEST = 53;
  /** RegularExpression Id. */
  int DIGIT = 54;
  /** RegularExpression Id. */
  int LETRA = 55;
  /** RegularExpression Id. */
  int NUMERO_ENTERO = 56;
  /** RegularExpression Id. */
  int NUMERO_DECIMAL = 57;
  /** RegularExpression Id. */
  int PALABRA = 58;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<MOV>",
    "\"RIGHT\"",
    "\"Put\"",
    "\"Pick\"",
    "\"Pop\"",
    "\"GO\"",
    "\"HOP\"",
    "\"left\"",
    "\"around\"",
    "\"front\"",
    "\"back\"",
    "\"up\"",
    "\"down\"",
    "\"defvar\"",
    "\"skip\"",
    "\"turn\"",
    "\"face\"",
    "\"move-dir\"",
    "\"run-dirs\"",
    "\"move-face\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"if\"",
    "\"loop\"",
    "\"repeat\"",
    "\"defun\"",
    "\"BALLOONS\"",
    "\"CHIPS\"",
    "\"facing?\"",
    "\"blocked?\"",
    "\"can-put?\"",
    "\"can-pick?\"",
    "\"can-move?\"",
    "\"iszero?\"",
    "\"not\"",
    "\"dim\"",
    "\"myxpos\"",
    "\"myypos\"",
    "\"mychips\"",
    "\"myballoons\"",
    "\"balloonshere\"",
    "\"chipsHere\"",
    "\"spaces\"",
    "\"null\"",
    "\"north\"",
    "\"south\"",
    "\"east\"",
    "\"west\"",
    "<DIGIT>",
    "<LETRA>",
    "<NUMERO_ENTERO>",
    "<NUMERO_DECIMAL>",
    "<PALABRA>",
    "\"=\"",
  };

}
